# Generated by Django 5.2.7 on 2025-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('patient',), name='uniq_paid_payment_per_patient'),
        ),
    ]
