# Generated by Django 5.2.7 on 2026-01-01 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('patients', '0001_initial'),
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treatment',
            name='unique_treatment_per_patient',
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(fields=('appointment',), name='unique_treatment_per_appointment'),
        ),
    ]
