# Generated by Django 5.2.7 on 2025-11-06 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_type', models.CharField(choices=[('initial', 'Initial Consultation'), ('follow_up', 'Follow-up Consultation')], default='initial', max_length=20)),
                ('type_seq', models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('case_followup_seq', models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('initial_appointment', models.ForeignKey(blank=True, help_text='For follow-up appointments, link to the initial appointment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_appointments', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
