# Generated by Django 5.2.7 on 2025-11-06 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, help_text='Follow-ups must reference a Treatment; initial appointments must leave this empty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='treatments.treatment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointment_type', 'type_seq'), name='unique_type_sequence_per_type'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('appointment_type', 'initial'), ('treatment__isnull', True)), models.Q(('appointment_type', 'follow_up'), ('treatment__isnull', False)), _connector='OR'), name='treatment_null_for_initial_required_for_followup'),
        ),
    ]
